{% set name = "airflow-ha" %}
{% set version = "1.6.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-ha/airflow_ha-{{ version }}.tar.gz
  sha256: c2ead6c9740e1e0e9969ab311a1876c83192c8ab6630232a278a804441abc68f

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - airflow-pydantic >=1.4,<1.6

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_ha

about:
  home: https://github.com/airflow-laminar/airflow-ha
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: High Availability (HA) DAG Utility
  description: High Availability (HA) DAG Utility
  dev_url: https://github.com/airflow-laminar/airflow-ha

extra:
  recipe-maintainers:
    - timkpaine
