{% set name = "airflow-ha" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-ha/airflow_ha-{{ version }}.tar.gz
  sha256: 5e40b61d6c655d6413b0823f860c27f7a8b99d25ec253c4194cea6ce0f4e70bb

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - apache-airflow >=2,<3

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - airflow_ha

about:
  home: https://github.com/airflow-laminar/airflow-ha
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: High Availability (HA) DAG Utility
  description: High Availability (HA) DAG Utility
  dev_url: https://github.com/airflow-laminar/airflow-ha

extra:
  recipe-maintainers:
    - timkpaine
