{% set name = "airflow-ha" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-ha/airflow_ha-{{ version }}.tar.gz
  sha256: 3545dd88c8fdda303538f540057bce0691f1431d3c51c80a905eb227aaf76710

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
  run_constrained:
    - apache-airflow >=2.8,<3

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_ha

about:
  home: https://github.com/airflow-laminar/airflow-ha
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: High Availability (HA) DAG Utility
  description: High Availability (HA) DAG Utility
  dev_url: https://github.com/airflow-laminar/airflow-ha

extra:
  recipe-maintainers:
    - timkpaine
